### ISSUE TITLE
Accessibility software

### ISSUE THREAD

**Issue by Jookia** [gianklug/wearewaylandnow#23]
Software like screen readers such as Orca are still pretty broken under Wayland, which seems like a pretty big deal to omit.

**Comment by ilmari-lauhakangas** [comment]
[Query for wayland in Orca issues](https://gitlab.gnome.org/GNOME/orca/-/issues/?sort=created_date&state=opened&search=wayland&first_page_size=20). Which ones would you nominate for blockers?

**Comment by Jookia** [comment]
https://gitlab.gnome.org/GNOME/orca/-/issues/455
https://gitlab.gnome.org/GNOME/orca/-/issues/440
https://gitlab.gnome.org/GNOME/orca/-/issues/483

At the very least

**Comment by gianklug** [comment]
Added a section on Orca:
https://github.com/gianklug/wearewaylandnow/commit/25efb7d89eff0bc769ff0ef42c78321264b9853d
