### ISSUE TITLE
Elkowars Wacky Widgets

### ISSUE THREAD

**Issue by runarcn** [gianklug/wearewaylandnow#25]
I was thinking of opening a PR to add [eww](https://github.com/elkowar/eww), but unsure where to put it? I was originaly thinking top bar/status bar, but I quickly realized it could to a lot more than just that :P

**Comment by gianklug** [comment]
Maybe some dedicated category for Widgets? 

`ags` could probably also go in there:
https://aylur.github.io/ags-docs/

**Comment by gianklug** [comment]
Added in https://github.com/gianklug/wearewaylandnow/commit/1e6911d6ca475aad830b191563c2c6013db8123f
