### ISSUE TITLE
OBS under wayland not useable if custom docks are needed (Twitch chat etc.)

### ISSUE THREAD

**Issue by 0fbcb238c0** [gianklug/wearewaylandnow#30]
As stated in the title, the custom browser docks feature of OBS, which is needed for integrating Youtube/Twitch chat etc., is not available under wayland due to the following issues:
https://github.com/obsproject/obs-browser/issues/279
https://github.com/chromiumembedded/cef/issues/2804

OBS under wayland is therefore not usable for streaming if custom browser docks are required.

**Comment by polluxau** [comment]
force it to run under xwayland with flatseal 

![image](https://github.com/user-attachments/assets/b1db4e7f-9c9b-4d16-94ec-e559b0002eb8)

or do this to force it also if the first one doesnt work
![image](https://github.com/user-attachments/assets/0a76a4bf-224d-47a8-b352-d43bcee48342)

**Comment by gianklug** [comment]
@0fbcb238c0 can you confirm this works?

**Comment by 0fbcb238c0** [comment]
Doing the first one indeed lets the options for custom browser docks show up. Since I am not a streamer myself I am not able to test if it works properly.
Forcing OBS to run on xorg will probably require the [xwaylandvideobridge](https://github.com/KDE/xwaylandvideobridge) to be installed, because OBS will otherwise not be able to capture windows or screens.

**Comment by polluxau** [comment]
> Doing the first one indeed lets the options for custom browser docks show up. Since I am not a streamer myself I am not able to test if it works properly.
> Forcing OBS to run on xorg will probably require the [xwaylandvideobridge](https://github.com/KDE/xwaylandvideobridge) to be installed, because OBS will otherwise not be able to capture windows or screens.

That is not required, you are able to use wayland capture still

**Comment by mihawk90** [comment]
> force it to run under xwayland

It should be noted this is not supported by upstream OBS and runs into various other issues when used.

**Comment by gianklug** [comment]
Maybe this could be added to a future "workarounds" page as in #28 

Not sure if the message about it being it should stay or be removed, as there are other tools also requiring workarounds.

**Comment by 0fbcb238c0** [comment]
A section for workarounds is definitely not a bad idea since there will me at least a few tools requiring workarounds to work properly under wayland. Another example: The discord client needs `XDG_SESSION_TYPE=x11` set, because the xwaylandvideobridge does not work properly with discord since a few versions ago.

**Comment by DaniloTakagi** [comment]
> force it to run under xwayland with flatseal
> 
> ![image](https://github.com/user-attachments/assets/b1db4e7f-9c9b-4d16-94ec-e559b0002eb8)
> 
> or do this to force it also if the first one doesnt work ![image](https://github.com/user-attachments/assets/0a76a4bf-224d-47a8-b352-d43bcee48342)

I switched from Mint (which still uses X11) to Fedora this week and this is my temporary salvation, thank you. I didn't notice any specific bugs doing this, and I can still capture my Wayland desktop and a game window.
